model_params:
  model: finetune
  params:
    arch: resnet34
    n_class: 1103
    image_size: &image_size 512
    pretrained: True

#  model: finetune_dla
#  params:
#    arch: dla34
#    n_class: 1103
#    pretrained: "imagenet"


#  model: finetune_cbam
#  params:
#    arch: dla34
#    n_class: 1103
#    pretrained: True


#  model: finetune_fishnet
#  params:
#    arch: fishnet99
#    n_class: 1103
#    pretrained: "./pretrained/fishnet/fishnet99_ckpt.tar"


args:
  expdir: ""
  logdir: "./logs/imet/"


stages:

  state_params:
    main_metric: &reduce_metric fbeta
    minimize_metric: False

  criterion_params:
    criterion: BCEFbetaFocalLoss
#    gamma: 2

  scheduler_params:
    scheduler: StepLR
    step_size: 5
    gamma: 0.1

  stage1:

    data_params:
      batch_size: 32
      num_workers: 4
      drop_last: False

      image_size: &image_size 512

      dataset:
        dataset_name: CsvDataset
        train:
          csv_file: "./imet/csv/kfold6/train_0.csv.gz"
          root: "/home/ubuntu2/ngxbac/imet/train/"
          # CsvDataset settings
          image_key: 'id'
          label_key: 'attribute_ids'
          mode: 'train'

        valid:
          csv_file: "./imet/csv/kfold6/valid_0.csv.gz"
          root: "/home/ubuntu2/ngxbac/imet/train/"
          # CsvDataset settings
          image_key: 'id'
          label_key: 'attribute_ids'
          mode: 'train'

    state_params:
      num_epochs: 1

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

    callbacks_params:
      loss:
        callback: LossCallback
      optimizer:
        callback: OptimizerCallback
      f1:
        callback: FbetaCallback
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 5

  stage2:

    data_params:
      batch_size: 32
      num_workers: 4
      drop_last: False

      image_size: *image_size

      dataset:
        dataset_name: CsvDataset
        train:
          csv_file: "./imet/csv/kfold6/train_0.csv.gz"
          root: "/home/ubuntu2/ngxbac/imet/train/"
          # CsvDataset settings
          image_key: 'id'
          label_key: 'attribute_ids'
          mode: 'train'

        valid:
          csv_file: "./imet/csv/kfold6/valid_0.csv.gz"
          root: "/home/ubuntu2/ngxbac/imet/train/"
          # CsvDataset settings
          image_key: 'id'
          label_key: 'attribute_ids'
          mode: 'train'

    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: Adam
      lr: 0.0001
      weight_decay: 0.0001

    callbacks_params:
      loss:
        callback: LossCallback
      optimizer:
        callback: OptimizerCallback
      f1:
        callback: FbetaCallback
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 5


  infer:
    data_params:
      num_workers: 4
      batch_size: 16
      drop_last: False

      image_size: *image_size

      dataset:
        dataset_name: CsvDataset
        infer:
          csv_file: "./data/sample_submission.csv"
          root: "/home/ubuntu2/ngxbac/imet/test/"

          # CsvDataset settings
          image_key: 'id'
          label_key: 'attribute_ids'
          mode: 'infer'

      use_tta: False

    callbacks_params:
      loader:
        callback: CheckpointCallback
      infer:
        callback: InferCallback
        out_dir: ""
        out_prefix: "/predicts/{suffix}.npy"