model_params:
  model: finetune
  params:
    arch: resnet34
    n_class: 1
    image_size: &image_size 224
    pretrained: True


args:
  expdir: ""
  logdir: "./logs/iwild_cam/"


stages:

  state_params:
    main_metric: &reduce_metric f1
    minimize_metric: False

  criterion_params:
    criterion: BCELossWightLogits

  scheduler_params:
    scheduler: ReduceLROnPlateau
    patience: 5
    factor: 0.1
    mode: max
    verbose: True

  stage1:

    data_params:
      batch_size: 32
      n_workers: 4
      drop_last: False

      train_csv: "/media/ngxbac/Bac2/fgvc6/iwildcam/csv/kfold/train_0.csv.gz"
      valid_csv: "/media/ngxbac/Bac2/fgvc6/iwildcam/csv/kfold/valid_0.csv.gz"
      root: "/media/ngxbac/Bac2/fgvc6/data/train_224/"
      image_size: *image_size

      # CsvDataset settings
      image_key: 'file_name'
      label_key: 'category_id'

    state_params:
      n_epochs: 5

    optimizer_params:
      optimizer: Adam
      lr: 0.0001
      weight_decay: 0.0001

    callbacks_params:
      loss:
        callback: LossCallback
      optimizer:
        callback: OptimizerCallback
      f1:
        callback: F1Callback
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback
        save_n_best: 5

  # tune
#  stage2:
#
#    data_params:
#      batch_size: 32
#      n_workers: 4
#      drop_last: False
#
#      train_csv: "/media/ngxbac/Bac2/fgvc6/iwildcam/csv/kfold/train_0.csv.gz"
#      valid_csv: "/media/ngxbac/Bac2/fgvc6/iwildcam/csv/kfold/valid_0.csv.gz"
#      root: "/media/ngxbac/Bac2/fgvc6/data/train_224/"
#      image_size: *image_size
#
#      # CsvDataset settings
#      image_key: 'file_name'
#      label_key: 'category_id'
#
#    state_params:
#      n_epochs: 5
#
#    callbacks_params:
#      loss:
#        callback: LossCallback
#      optimizer:
#        callback: OptimizerCallback
#      f1:
#        callback: F1Callback
#      scheduler:
#        callback: SchedulerCallback
#        reduce_metric: *reduce_metric
#      saver:
#        callback: CheckpointCallback
#        save_n_best: 5
#
#    optimizer_params:
#      optimizer: Adam
#      lr: 0.0001
#      weight_decay: 0.0001

  infer:
    data_params:
      n_workers: 4
      batch_size: 64
      drop_last: False

      infer_csv: "/media/ngxbac/Bac2/fgvc6/data/test.csv"
      root: "/media/ngxbac/Bac2/fgvc6/data/test_224/"

      image_size: *image_size

      # CsvDataset settings
      image_key: 'file_name'
      label_key: 'category_id'

      use_tta: True

    callbacks_params:
      loader:
        callback: CheckpointCallback
      infer:
        callback: InferCallback
        out_dir: ""
        out_prefix: "/predicts/{suffix}.npy"
