model_params:
  model: finetune
  params:
    arch: resnet34
    n_class: 6
    image_size: &image_size 224
    pretrained: True


args:
  expdir: ""
  logdir: &logdir "./logs/intel_scene"
  batch_size: 32

stages:
  infer:
    data_params:
      n_workers: 4
      batch_size: 64
      infer_csv: "/media/ngxbac/Bac2/fgvc6/data/test.csv"
      root: "/media/ngxbac/Bac2/fgvc6/data/test_224/"
      root_external: "/media/ngxbac/Bac2/fgvc6/data/iWildCam_2019_iNat_Idaho/"

      image_size: *image_size

      # CsvDataset settings
      image_key: 'file_name'
      label_key: 'category_id'

      use_tta: True

    callbacks_params:
      loader:
        callback: CheckpointCallback
      infer:
        callback: InferCallback
        out_dir: *logdir
        out_prefix: "/predictions/{suffix}.npy"